/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_or = 5,
  anon_sym_and = 6,
  anon_sym_EQ_EQ = 7,
  anon_sym_PLUS = 8,
  anon_sym_DASH = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_DOT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  sym_number = 17,
  sym_string = 18,
  sym_character = 19,
  sym_comment = 20,
  anon_sym_SEMI = 21,
  aux_sym__separator_token1 = 22,
  sym_source_file = 23,
  sym_declaration = 24,
  sym_map = 25,
  sym__expression = 26,
  sym_binary_expression = 27,
  sym_unary_expression = 28,
  sym_application_expression = 29,
  sym__postfix_expression = 30,
  sym_field_expression = 31,
  sym__primary_expression = 32,
  sym_parenthesized_expression = 33,
  sym_boolean = 34,
  sym__separator = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_source_file_repeat2 = 37,
  aux_sym_application_expression_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_character] = "character",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [aux_sym__separator_token1] = "_separator_token1",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_map] = "map",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_application_expression] = "application_expression",
  [sym__postfix_expression] = "_postfix_expression",
  [sym_field_expression] = "field_expression",
  [sym__primary_expression] = "_primary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_boolean] = "boolean",
  [sym__separator] = "_separator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_application_expression_repeat1] = "application_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_character] = sym_character,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym__separator_token1] = aux_sym__separator_token1,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_map] = sym_map,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_application_expression] = sym_application_expression,
  [sym__postfix_expression] = sym__postfix_expression,
  [sym_field_expression] = sym_field_expression,
  [sym__primary_expression] = sym__primary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_boolean] = sym_boolean,
  [sym__separator] = sym__separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_application_expression_repeat1] = aux_sym_application_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__separator_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_application_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__postfix_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_field_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_application_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_field = 2,
  field_function = 3,
  field_left = 4,
  field_name = 5,
  field_operand = 6,
  field_operator = 7,
  field_right = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_field] = "field",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_operand, 1},
    {field_operator, 0},
  [4] =
    {field_argument, 0},
  [5] =
    {field_argument, 1, .inherited = true},
    {field_function, 0},
  [7] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [10] =
    {field_field, 2},
    {field_value, 0},
  [12] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 49,
        '\r', 1,
        '"', 2,
        '\'', 5,
        '(', 28,
        ')', 29,
        '*', 25,
        '+', 23,
        '-', 24,
        '.', 27,
        '/', 26,
        '0', 33,
        ';', 48,
        '=', 19,
        '@', 3,
        '{', 20,
        '}', 21,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead > 0x1f &&
          lookahead != '"' &&
          lookahead != 0x7f) ADVANCE(4);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(2);
      END_STATE();
    case 14:
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead > 0x1f &&
          lookahead != 0x7f) ADVANCE(4);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 49,
        '\r', 1,
        '"', 2,
        '\'', 5,
        '(', 28,
        ')', 29,
        '*', 25,
        '+', 23,
        '-', 24,
        '.', 27,
        '/', 26,
        '0', 33,
        ';', 48,
        '=', 8,
        '@', 3,
        '}', 21,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(16);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 11,
        'B', 35,
        'b', 35,
        'O', 36,
        'o', 36,
        'X', 34,
        'x', 34,
        'E', 32,
        'P', 32,
        'e', 32,
        'p', 32,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(32);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(36);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'P' ||
          lookahead == 'e' ||
          lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__separator_token1);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'o') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_character] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym__separator_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_declaration] = STATE(43),
    [sym__separator] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(9),
    [aux_sym__separator_token1] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__postfix_expression] = STATE(6),
    [sym_field_expression] = STATE(6),
    [sym__primary_expression] = STATE(6),
    [sym_parenthesized_expression] = STATE(6),
    [sym_boolean] = STATE(6),
    [aux_sym_application_expression_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(11),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
    [sym_character] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(11),
    [aux_sym__separator_token1] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__postfix_expression] = STATE(6),
    [sym_field_expression] = STATE(6),
    [sym__primary_expression] = STATE(6),
    [sym_parenthesized_expression] = STATE(6),
    [sym_boolean] = STATE(6),
    [aux_sym_application_expression_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(30),
    [anon_sym_and] = ACTIONS(30),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(30),
    [anon_sym_LPAREN] = ACTIONS(32),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_number] = ACTIONS(38),
    [sym_string] = ACTIONS(38),
    [sym_character] = ACTIONS(38),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(25),
    [aux_sym__separator_token1] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym__postfix_expression] = STATE(6),
    [sym_field_expression] = STATE(6),
    [sym__primary_expression] = STATE(6),
    [sym_parenthesized_expression] = STATE(6),
    [sym_boolean] = STATE(6),
    [aux_sym_application_expression_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_or] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
    [sym_character] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(41),
    [aux_sym__separator_token1] = ACTIONS(41),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(47),
    [anon_sym_and] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_true] = ACTIONS(47),
    [anon_sym_false] = ACTIONS(47),
    [sym_number] = ACTIONS(45),
    [sym_string] = ACTIONS(45),
    [sym_character] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(45),
    [aux_sym__separator_token1] = ACTIONS(45),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(51),
    [anon_sym_and] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_number] = ACTIONS(49),
    [sym_string] = ACTIONS(49),
    [sym_character] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(49),
    [aux_sym__separator_token1] = ACTIONS(49),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_or] = ACTIONS(55),
    [anon_sym_and] = ACTIONS(55),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_true] = ACTIONS(55),
    [anon_sym_false] = ACTIONS(55),
    [sym_number] = ACTIONS(53),
    [sym_string] = ACTIONS(53),
    [sym_character] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(53),
    [aux_sym__separator_token1] = ACTIONS(53),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_or] = ACTIONS(59),
    [anon_sym_and] = ACTIONS(59),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(59),
    [anon_sym_false] = ACTIONS(59),
    [sym_number] = ACTIONS(57),
    [sym_string] = ACTIONS(57),
    [sym_character] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(57),
    [aux_sym__separator_token1] = ACTIONS(57),
  },
  [STATE(9)] = {
    [sym_map] = STATE(46),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_application_expression] = STATE(24),
    [sym__postfix_expression] = STATE(2),
    [sym_field_expression] = STATE(2),
    [sym__primary_expression] = STATE(2),
    [sym_parenthesized_expression] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(67),
    [sym_string] = ACTIONS(67),
    [sym_character] = ACTIONS(67),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(18), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [35] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(21), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [70] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(22), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [105] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(25), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [140] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(19), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [175] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(23), 4,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_application_expression,
    STATE(2), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [210] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(20), 1,
      sym_unary_expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 3,
      sym_number,
      sym_string,
      sym_character,
    STATE(17), 5,
      sym__postfix_expression,
      sym_field_expression,
      sym__primary_expression,
      sym_parenthesized_expression,
      sym_boolean,
  [242] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [287] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_SLASH,
    ACTIONS(77), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [307] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [327] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(85), 1,
      anon_sym_and,
    ACTIONS(87), 1,
      anon_sym_EQ_EQ,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [355] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_EQ_EQ,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [381] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [405] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(85), 1,
      anon_sym_and,
    ACTIONS(87), 1,
      anon_sym_EQ_EQ,
    ACTIONS(93), 1,
      anon_sym_or,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [434] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(85), 1,
      anon_sym_and,
    ACTIONS(87), 1,
      anon_sym_EQ_EQ,
    ACTIONS(93), 1,
      anon_sym_or,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [460] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [481] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(103), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(37), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [500] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      sym_declaration,
    ACTIONS(108), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(34), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [521] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [542] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [563] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
    ACTIONS(116), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [601] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [622] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [643] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [664] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [685] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(51), 1,
      sym_declaration,
    ACTIONS(99), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(32), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [703] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(129), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(30), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [721] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(131), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(35), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [739] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(131), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(35), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [757] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(133), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(33), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [775] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(133), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(33), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [793] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(135), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(29), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [811] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(137), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(36), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [829] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(139), 2,
      anon_sym_SEMI,
      aux_sym__separator_token1,
    STATE(31), 2,
      sym__separator,
      aux_sym_source_file_repeat1,
  [847] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [877] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym__separator_token1,
  [917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_identifier,
  [924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_EQ,
  [931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 35,
  [SMALL_STATE(12)] = 70,
  [SMALL_STATE(13)] = 105,
  [SMALL_STATE(14)] = 140,
  [SMALL_STATE(15)] = 175,
  [SMALL_STATE(16)] = 210,
  [SMALL_STATE(17)] = 242,
  [SMALL_STATE(18)] = 265,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 307,
  [SMALL_STATE(21)] = 327,
  [SMALL_STATE(22)] = 355,
  [SMALL_STATE(23)] = 381,
  [SMALL_STATE(24)] = 405,
  [SMALL_STATE(25)] = 434,
  [SMALL_STATE(26)] = 460,
  [SMALL_STATE(27)] = 481,
  [SMALL_STATE(28)] = 500,
  [SMALL_STATE(29)] = 521,
  [SMALL_STATE(30)] = 542,
  [SMALL_STATE(31)] = 563,
  [SMALL_STATE(32)] = 584,
  [SMALL_STATE(33)] = 601,
  [SMALL_STATE(34)] = 622,
  [SMALL_STATE(35)] = 643,
  [SMALL_STATE(36)] = 664,
  [SMALL_STATE(37)] = 685,
  [SMALL_STATE(38)] = 703,
  [SMALL_STATE(39)] = 721,
  [SMALL_STATE(40)] = 739,
  [SMALL_STATE(41)] = 757,
  [SMALL_STATE(42)] = 775,
  [SMALL_STATE(43)] = 793,
  [SMALL_STATE(44)] = 811,
  [SMALL_STATE(45)] = 829,
  [SMALL_STATE(46)] = 847,
  [SMALL_STATE(47)] = 857,
  [SMALL_STATE(48)] = 867,
  [SMALL_STATE(49)] = 877,
  [SMALL_STATE(50)] = 887,
  [SMALL_STATE(51)] = 897,
  [SMALL_STATE(52)] = 907,
  [SMALL_STATE(53)] = 917,
  [SMALL_STATE(54)] = 924,
  [SMALL_STATE(55)] = 931,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7), SHIFT_REPEAT(13),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7), SHIFT_REPEAT(7),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_application_expression_repeat1, 2, 0, 7), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application_expression, 2, 0, 4),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application_expression, 2, 0, 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_expression, 3, 0, 6),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_expression, 3, 0, 6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_expression_repeat1, 1, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_application_expression_repeat1, 1, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(37),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 6, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [155] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "eon",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
